### ISSUE TITLE
USER STORY: Create database

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#11]
As a **developer** I want to **set up and configure a database** so that **I can store and manage the application data securely and efficiently**.

---
**Acceptance criteria:**
- Choose an appropriate database for the project 
- Define models representing the data structure required by the application
- Ensure database credentials are stored securely

---
**Tasks:**
- [x] Decide on a database to use and create it
- [x] Create and define django models
- [x] Secure the database access

---
**EPIC: **
[Basic Website and Database Structure](https://github.com/queenisabaer/wishlist/issues/3)
