### ISSUE TITLE
USER STORY: User login

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#13]
As a **registered user,** I want to **log in to my account** so that **I can create, read, update and delete my wish list(s)**.
As a **registered user** I want to **manage my profile** so that **I can update my account**.

---
**Acceptance criteria:**
- The login form should accept username and password
- The login form should be easy to access
- After successful login, the user should be redirected to their dashboard and have the possibility to logout.
- The dashboard should include a button to update the profile. 

---
**Tasks:**
- [x] Create a login form
- [x] Add dashboard for registered users
- [x] Add update button

---
**EPIC: **
[User authentication](https://github.com/queenisabaer/wishlist/issues/4)
