### ISSUE TITLE
USER STORY: Delete wishlist

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#17]
As a **registered user**, I want to **be able to delete a wishlist** so that **I can remove outdated or unnecessary lists**.

---
**Acceptance criteria:**
- Wishlist contains delete button
- The delete action should prompt for confirmation
- Once confirmed, the wishlist should be removed from the user's dashboard and removed from the database

---
**Tasks:**
- [x] Add delete Button and its functionality to wishlist
- [x] Create prompt for confirmation
- [x] Add functionality so that deleted wishlists are removed from dashboard of user

---
**EPIC: **
[Wishlist Management](https://github.com/queenisabaer/wishlist/issues/5)
