### ISSUE TITLE
USER STORY: Add item to wishlist

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#18]
As a **user**, I want to **add items to my wishlist** so that **I can keep track of things I want**.

---
**Acceptance criteria:**
- The item addition form should include fields for item name, description, quantity, purchase link and the possibility to reserve the item
- The new item should appear in the wishlist.

---
**Tasks:**
- [x] Implement backend functionality for adding Items to a wishlist
- [x] Develop frontend interface for adding items to a wishlist
- [x] ensure new item appears on wishlist

---
**EPIC: **
[Wishlist Management](https://github.com/queenisabaer/wishlist/issues/5)
