### ISSUE TITLE
USER STORY: Edit Item

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#19]
As a **registered user**, I want to **edit items in my wishlist** so that **I can update their details**.
---
**Acceptance criteria:**
- The item edit form should allow changes to the item name, description, and purchase link.
- Changes should be saved and reflected in the wishlist.
---
**Tasks:**
- [ ]  Implement backend functionality for editing items in a wishlist
- [ ] Develop frontend interface for editing items in a wishlist
- [ ]  ensure update of items is reflected on wishlist 

---
**EPIC: **
[Wishlist Management](https://github.com/queenisabaer/wishlist/issues/5)
