### ISSUE TITLE
USER STORY: Reserve an item

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#23]
As a **registered user**, I want to **reserve an item of a wishlist**, so that **no other user will purchase this**.

---
**Acceptance criteria:**
- Users should be able to mark an item in a wishlist as reserved/unreserved
- Reserved items should display a visual indicator

---
**Tasks:**
- [ ] Implement backend functionality for reserving an item of a wishlist
- [ ] Develop frontend interface for reservingan item
- [ ] Ensure database reflects reservation status

---
**EPIC: **
[Wishlist management](https://github.com/queenisabaer/wishlist/issues/5)
