### ISSUE TITLE
USER STORY: Collaborate on a wishlist

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#24]
As a **registered user**, I want to **be able to collaborate on a wishlist with others** so that **we can collectively manage it**.

---
**Acceptance criteria:**
- Collaborators should be able to add, edit, and delete items in the shared wishlist.

---
**Tasks:**
- [ ] Implement backend functionality for collaborating on a  wishlist
- [ ] Develop frontend interface for collaborating on a wishlist
- [ ] ensure that the editing of a wishlist is reflected on the wishlist for all collaborators
---
**EPIC: **
[Wishlist Management](https://github.com/queenisabaer/wishlist/issues/5)
