### ISSUE TITLE
EPIC 2: Basic Website and Database Structure 

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#3]
**Description:**
Create a basic website structure and configure the database schema
---
**Related User Stories:**
- [x] [Admin Authorization ](https://github.com/queenisabaer/wishlist/issues/8)
- [x] [Landing Page](https://github.com/queenisabaer/wishlist/issues/9)
- [x] [Define database schema ](https://github.com/queenisabaer/wishlist/issues/10)
- [x] [Create database ](https://github.com/queenisabaer/wishlist/issues/11)
