### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by queenisabaer** [queenisabaer/wishlist#9]
As a **new website user** I **am able to identify the website's goal** so that **I can decide whether to continue or leave**.
As a **frequent website user** I can **easily login to my account** so that **I have access to my wish lists and items I want to purchase**.

---
**Acceptance criteria:**
- The website should display a clear and concise description or tagline that communicates the website's primary purpose within the first few seconds of viewing
- It should include visual elements and navigational cues that help explain the website's goal and functionality.

---
**Tasks:**
- [x] Design the landing page layout.
- [x] Create login functionality 
- [x] Implement the landing page structure.
- [x] Add content to the landing page

---
**EPIC: **
[Basic Website and Database Structure](https://github.com/queenisabaer/wishlist/issues/3)
